# Generated by Django 4.2 on 2025-06-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник')], default='employee', max_length=20, verbose_name='Роль'),
        ),
    ]
